// Curated list of Indian higher-ed institutions.
//
// Covers — as required by Phase 1:
//   • All 23 IITs, 31 NITs, 26 IIITs (centrally funded)
//   • All 20 IIMs
//   • All 7 IISERs + IISc Bangalore
//   • All 25 NLUs
//   • SRCC + prominent DU constituent colleges
//   • Top NIRF Engineering / Management / Commerce / Law / Science / Medical
//   • Major state universities (JNU, JU, AU, Anna, MAHE, etc.)
//
// For long-tail colleges not in this list, the signup picker has an
// "Add my college" flow that creates rows with `verified=false`, surfaced
// in the admin queue.
//
// To extend to the full AISHE registry (~50k institutions), download the
// public dataset from https://aishe.gov.in and pipe it through a script
// that fills `name`, `state`, `category` and bulk-inserts via Prisma's
// createMany with skipDuplicates. The seed function below already does
// the right thing — just feed it more rows.

export type InstitutionSeed = {
  name: string;
  shortName?: string;
  domain?: string;
  category:
    | 'engineering'
    | 'management'
    | 'law'
    | 'science'
    | 'commerce'
    | 'arts'
    | 'medical'
    | 'other';
  nirfRank?: number;
  state?: string;
  city?: string;
  tier?: string;
};

// ---------- IITs (all 23) ----------
const IITS: InstitutionSeed[] = [
  {
    name: 'Indian Institute of Technology Madras',
    shortName: 'IIT-M',
    domain: 'iitm.ac.in',
    category: 'engineering',
    nirfRank: 1,
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Delhi',
    shortName: 'IIT-D',
    domain: 'iitd.ac.in',
    category: 'engineering',
    nirfRank: 2,
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Bombay',
    shortName: 'IIT-B',
    domain: 'iitb.ac.in',
    category: 'engineering',
    nirfRank: 3,
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Kanpur',
    shortName: 'IIT-K',
    domain: 'iitk.ac.in',
    category: 'engineering',
    nirfRank: 4,
    state: 'Uttar Pradesh',
    city: 'Kanpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Kharagpur',
    shortName: 'IIT-KGP',
    domain: 'iitkgp.ac.in',
    category: 'engineering',
    nirfRank: 5,
    state: 'West Bengal',
    city: 'Kharagpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Roorkee',
    shortName: 'IIT-R',
    domain: 'iitr.ac.in',
    category: 'engineering',
    nirfRank: 6,
    state: 'Uttarakhand',
    city: 'Roorkee',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Guwahati',
    shortName: 'IIT-G',
    domain: 'iitg.ac.in',
    category: 'engineering',
    nirfRank: 7,
    state: 'Assam',
    city: 'Guwahati',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Hyderabad',
    shortName: 'IIT-H',
    domain: 'iith.ac.in',
    category: 'engineering',
    nirfRank: 8,
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology (BHU) Varanasi',
    shortName: 'IIT-BHU',
    domain: 'iitbhu.ac.in',
    category: 'engineering',
    nirfRank: 15,
    state: 'Uttar Pradesh',
    city: 'Varanasi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Indore',
    shortName: 'IIT-I',
    domain: 'iiti.ac.in',
    category: 'engineering',
    nirfRank: 16,
    state: 'Madhya Pradesh',
    city: 'Indore',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology (ISM) Dhanbad',
    shortName: 'IIT-ISM',
    domain: 'iitism.ac.in',
    category: 'engineering',
    nirfRank: 17,
    state: 'Jharkhand',
    city: 'Dhanbad',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Ropar',
    shortName: 'IIT-RPR',
    domain: 'iitrpr.ac.in',
    category: 'engineering',
    nirfRank: 22,
    state: 'Punjab',
    city: 'Rupnagar',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Gandhinagar',
    shortName: 'IIT-GN',
    domain: 'iitgn.ac.in',
    category: 'engineering',
    nirfRank: 25,
    state: 'Gujarat',
    city: 'Gandhinagar',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Patna',
    shortName: 'IIT-P',
    domain: 'iitp.ac.in',
    category: 'engineering',
    nirfRank: 41,
    state: 'Bihar',
    city: 'Patna',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Mandi',
    shortName: 'IIT-Mandi',
    domain: 'iitmandi.ac.in',
    category: 'engineering',
    nirfRank: 31,
    state: 'Himachal Pradesh',
    city: 'Mandi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Bhubaneswar',
    shortName: 'IIT-BBS',
    domain: 'iitbbs.ac.in',
    category: 'engineering',
    nirfRank: 40,
    state: 'Odisha',
    city: 'Bhubaneswar',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Jodhpur',
    shortName: 'IIT-J',
    domain: 'iitj.ac.in',
    category: 'engineering',
    nirfRank: 47,
    state: 'Rajasthan',
    city: 'Jodhpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Tirupati',
    shortName: 'IIT-TP',
    domain: 'iittp.ac.in',
    category: 'engineering',
    state: 'Andhra Pradesh',
    city: 'Tirupati',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Palakkad',
    shortName: 'IIT-PKD',
    domain: 'iitpkd.ac.in',
    category: 'engineering',
    state: 'Kerala',
    city: 'Palakkad',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Bhilai',
    shortName: 'IIT-BH',
    domain: 'iitbhilai.ac.in',
    category: 'engineering',
    state: 'Chhattisgarh',
    city: 'Bhilai',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Goa',
    shortName: 'IIT-Goa',
    domain: 'iitgoa.ac.in',
    category: 'engineering',
    state: 'Goa',
    city: 'Ponda',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Jammu',
    shortName: 'IIT-JMU',
    domain: 'iitjammu.ac.in',
    category: 'engineering',
    state: 'Jammu and Kashmir',
    city: 'Jammu',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Technology Dharwad',
    shortName: 'IIT-DH',
    domain: 'iitdh.ac.in',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Dharwad',
    tier: 'tier-1',
  },
];

// ---------- NITs (all 31) ----------
const NITS: InstitutionSeed[] = [
  {
    name: 'National Institute of Technology Tiruchirappalli',
    shortName: 'NIT-T',
    domain: 'nitt.edu',
    category: 'engineering',
    nirfRank: 9,
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Karnataka, Surathkal',
    shortName: 'NIT-K',
    domain: 'nitk.edu.in',
    category: 'engineering',
    nirfRank: 17,
    state: 'Karnataka',
    city: 'Mangalore',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Rourkela',
    shortName: 'NIT-RKL',
    domain: 'nitrkl.ac.in',
    category: 'engineering',
    nirfRank: 19,
    state: 'Odisha',
    city: 'Rourkela',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Warangal',
    shortName: 'NIT-W',
    domain: 'nitw.ac.in',
    category: 'engineering',
    nirfRank: 21,
    state: 'Telangana',
    city: 'Warangal',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Calicut',
    shortName: 'NIT-C',
    domain: 'nitc.ac.in',
    category: 'engineering',
    nirfRank: 25,
    state: 'Kerala',
    city: 'Kozhikode',
    tier: 'tier-1',
  },
  {
    name: 'Visvesvaraya National Institute of Technology Nagpur',
    shortName: 'VNIT',
    domain: 'vnit.ac.in',
    category: 'engineering',
    nirfRank: 46,
    state: 'Maharashtra',
    city: 'Nagpur',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Silchar',
    shortName: 'NIT-S',
    domain: 'nits.ac.in',
    category: 'engineering',
    nirfRank: 51,
    state: 'Assam',
    city: 'Silchar',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Durgapur',
    shortName: 'NIT-DGP',
    domain: 'nitdgp.ac.in',
    category: 'engineering',
    nirfRank: 53,
    state: 'West Bengal',
    city: 'Durgapur',
    tier: 'tier-1',
  },
  {
    name: 'Malaviya National Institute of Technology Jaipur',
    shortName: 'MNIT',
    domain: 'mnit.ac.in',
    category: 'engineering',
    nirfRank: 50,
    state: 'Rajasthan',
    city: 'Jaipur',
    tier: 'tier-1',
  },
  {
    name: 'Motilal Nehru National Institute of Technology Allahabad',
    shortName: 'MNNIT',
    domain: 'mnnit.ac.in',
    category: 'engineering',
    nirfRank: 92,
    state: 'Uttar Pradesh',
    city: 'Prayagraj',
    tier: 'tier-1',
  },
  {
    name: 'Sardar Vallabhbhai National Institute of Technology Surat',
    shortName: 'SVNIT',
    domain: 'svnit.ac.in',
    category: 'engineering',
    state: 'Gujarat',
    city: 'Surat',
    tier: 'tier-1',
  },
  {
    name: 'Maulana Azad National Institute of Technology Bhopal',
    shortName: 'MANIT',
    domain: 'manit.ac.in',
    category: 'engineering',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Patna',
    shortName: 'NIT-Patna',
    domain: 'nitp.ac.in',
    category: 'engineering',
    state: 'Bihar',
    city: 'Patna',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Kurukshetra',
    shortName: 'NIT-KKR',
    domain: 'nitkkr.ac.in',
    category: 'engineering',
    state: 'Haryana',
    city: 'Kurukshetra',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Jamshedpur',
    shortName: 'NIT-JSR',
    domain: 'nitjsr.ac.in',
    category: 'engineering',
    state: 'Jharkhand',
    city: 'Jamshedpur',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Raipur',
    shortName: 'NIT-RPR',
    domain: 'nitrr.ac.in',
    category: 'engineering',
    state: 'Chhattisgarh',
    city: 'Raipur',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Hamirpur',
    shortName: 'NIT-HMR',
    domain: 'nith.ac.in',
    category: 'engineering',
    state: 'Himachal Pradesh',
    city: 'Hamirpur',
    tier: 'tier-1',
  },
  {
    name: 'Dr. B. R. Ambedkar National Institute of Technology Jalandhar',
    shortName: 'NIT-J',
    domain: 'nitj.ac.in',
    category: 'engineering',
    state: 'Punjab',
    city: 'Jalandhar',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Srinagar',
    shortName: 'NIT-SRI',
    domain: 'nitsri.ac.in',
    category: 'engineering',
    state: 'Jammu and Kashmir',
    city: 'Srinagar',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Agartala',
    shortName: 'NIT-AGT',
    domain: 'nita.ac.in',
    category: 'engineering',
    state: 'Tripura',
    city: 'Agartala',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Meghalaya',
    shortName: 'NIT-MEG',
    domain: 'nitm.ac.in',
    category: 'engineering',
    state: 'Meghalaya',
    city: 'Shillong',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Manipur',
    shortName: 'NIT-MN',
    domain: 'nitmanipur.ac.in',
    category: 'engineering',
    state: 'Manipur',
    city: 'Imphal',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Mizoram',
    shortName: 'NIT-MZ',
    domain: 'nitmz.ac.in',
    category: 'engineering',
    state: 'Mizoram',
    city: 'Aizawl',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Nagaland',
    shortName: 'NIT-NL',
    domain: 'nitnagaland.ac.in',
    category: 'engineering',
    state: 'Nagaland',
    city: 'Dimapur',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Sikkim',
    shortName: 'NIT-SKM',
    domain: 'nitsikkim.ac.in',
    category: 'engineering',
    state: 'Sikkim',
    city: 'Ravangla',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Arunachal Pradesh',
    shortName: 'NIT-AP',
    domain: 'nitap.ac.in',
    category: 'engineering',
    state: 'Arunachal Pradesh',
    city: 'Yupia',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Goa',
    shortName: 'NIT-Goa',
    domain: 'nitgoa.ac.in',
    category: 'engineering',
    state: 'Goa',
    city: 'Ponda',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Puducherry',
    shortName: 'NIT-PY',
    domain: 'nitpy.ac.in',
    category: 'engineering',
    state: 'Puducherry',
    city: 'Karaikal',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Uttarakhand',
    shortName: 'NIT-UK',
    domain: 'nituk.ac.in',
    category: 'engineering',
    state: 'Uttarakhand',
    city: 'Srinagar (Garhwal)',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Delhi',
    shortName: 'NIT-Delhi',
    domain: 'nitdelhi.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Technology Andhra Pradesh',
    shortName: 'NIT-AP',
    domain: 'nitandhra.ac.in',
    category: 'engineering',
    state: 'Andhra Pradesh',
    city: 'Tadepalligudem',
    tier: 'tier-1',
  },
];

// ---------- IIITs (centrally funded; major ones) ----------
const IIITS: InstitutionSeed[] = [
  {
    name: 'International Institute of Information Technology Hyderabad',
    shortName: 'IIIT-H',
    domain: 'iiit.ac.in',
    category: 'engineering',
    nirfRank: 47,
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'Indraprastha Institute of Information Technology Delhi',
    shortName: 'IIIT-D',
    domain: 'iiitd.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'International Institute of Information Technology Bangalore',
    shortName: 'IIIT-B',
    domain: 'iiitb.ac.in',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'Atal Bihari Vajpayee Indian Institute of Information Technology and Management Gwalior',
    shortName: 'ABV-IIITM',
    domain: 'iiitm.ac.in',
    category: 'engineering',
    state: 'Madhya Pradesh',
    city: 'Gwalior',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Allahabad',
    shortName: 'IIIT-A',
    domain: 'iiita.ac.in',
    category: 'engineering',
    state: 'Uttar Pradesh',
    city: 'Prayagraj',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Design and Manufacturing Jabalpur',
    shortName: 'IIITDM-J',
    domain: 'iiitdmj.ac.in',
    category: 'engineering',
    state: 'Madhya Pradesh',
    city: 'Jabalpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Design and Manufacturing Kancheepuram',
    shortName: 'IIITDM-K',
    domain: 'iiitdm.ac.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Lucknow',
    shortName: 'IIIT-L',
    domain: 'iiitl.ac.in',
    category: 'engineering',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Guwahati',
    shortName: 'IIIT-G',
    domain: 'iiitg.ac.in',
    category: 'engineering',
    state: 'Assam',
    city: 'Guwahati',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Sri City',
    shortName: 'IIIT-SC',
    domain: 'iiits.in',
    category: 'engineering',
    state: 'Andhra Pradesh',
    city: 'Chittoor',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Una',
    shortName: 'IIIT-Una',
    domain: 'iiitu.ac.in',
    category: 'engineering',
    state: 'Himachal Pradesh',
    city: 'Una',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Vadodara',
    shortName: 'IIIT-V',
    domain: 'iiitvadodara.ac.in',
    category: 'engineering',
    state: 'Gujarat',
    city: 'Gandhinagar',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Kota',
    shortName: 'IIIT-Kota',
    domain: 'iiitkota.ac.in',
    category: 'engineering',
    state: 'Rajasthan',
    city: 'Kota',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Tiruchirappalli',
    shortName: 'IIIT-T',
    domain: 'iiitt.ac.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Nagpur',
    shortName: 'IIIT-N',
    domain: 'iiitn.ac.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Nagpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Pune',
    shortName: 'IIIT-P',
    domain: 'iiitp.ac.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Bhagalpur',
    shortName: 'IIIT-BG',
    domain: 'iiitbh.ac.in',
    category: 'engineering',
    state: 'Bihar',
    city: 'Bhagalpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Bhopal',
    shortName: 'IIIT-BPL',
    domain: 'iiitbhopal.ac.in',
    category: 'engineering',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Dharwad',
    shortName: 'IIIT-DH',
    domain: 'iiitdwd.ac.in',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Dharwad',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Kalyani',
    shortName: 'IIIT-KLY',
    domain: 'iiitkalyani.ac.in',
    category: 'engineering',
    state: 'West Bengal',
    city: 'Kalyani',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Kottayam',
    shortName: 'IIIT-KTM',
    domain: 'iiitkottayam.ac.in',
    category: 'engineering',
    state: 'Kerala',
    city: 'Kottayam',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Manipur',
    shortName: 'IIIT-Mnp',
    domain: 'iiitmanipur.ac.in',
    category: 'engineering',
    state: 'Manipur',
    city: 'Imphal',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Ranchi',
    shortName: 'IIIT-Ran',
    domain: 'iiitranchi.ac.in',
    category: 'engineering',
    state: 'Jharkhand',
    city: 'Ranchi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Senapati Manipur',
    shortName: 'IIIT-Sen',
    domain: 'iiitsenapati.ac.in',
    category: 'engineering',
    state: 'Manipur',
    city: 'Senapati',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Surat',
    shortName: 'IIIT-Sur',
    domain: 'iiitsurat.ac.in',
    category: 'engineering',
    state: 'Gujarat',
    city: 'Surat',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Information Technology Sonepat',
    shortName: 'IIIT-SNP',
    domain: 'iiitsonepat.ac.in',
    category: 'engineering',
    state: 'Haryana',
    city: 'Sonepat',
    tier: 'tier-1',
  },
];

// ---------- Other top engineering (NIRF & well-known) ----------
const OTHER_ENG: InstitutionSeed[] = [
  {
    name: 'Birla Institute of Technology and Science, Pilani',
    shortName: 'BITS Pilani',
    domain: 'pilani.bits-pilani.ac.in',
    category: 'engineering',
    nirfRank: 20,
    state: 'Rajasthan',
    city: 'Pilani',
    tier: 'tier-1',
  },
  {
    name: 'BITS Pilani K.K. Birla Goa Campus',
    shortName: 'BITS Goa',
    domain: 'goa.bits-pilani.ac.in',
    category: 'engineering',
    state: 'Goa',
    city: 'Sancoale',
    tier: 'tier-1',
  },
  {
    name: 'BITS Pilani Hyderabad Campus',
    shortName: 'BITS Hyd',
    domain: 'hyderabad.bits-pilani.ac.in',
    category: 'engineering',
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'Vellore Institute of Technology',
    shortName: 'VIT Vellore',
    domain: 'vitstudent.ac.in',
    category: 'engineering',
    nirfRank: 11,
    state: 'Tamil Nadu',
    city: 'Vellore',
    tier: 'tier-2',
  },
  {
    name: 'VIT Chennai',
    shortName: 'VIT-C',
    domain: 'vit.ac.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-2',
  },
  {
    name: 'Jadavpur University',
    shortName: 'JU',
    domain: 'jaduniv.edu.in',
    category: 'engineering',
    nirfRank: 12,
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: 'Anna University',
    shortName: 'AU',
    domain: 'annauniv.edu',
    category: 'engineering',
    nirfRank: 13,
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Delhi Technological University',
    shortName: 'DTU',
    domain: 'dtu.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Netaji Subhas University of Technology',
    shortName: 'NSUT',
    domain: 'nsut.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Indraprastha Institute of Information Technology',
    shortName: 'IIIT-D',
    domain: 'iiitd.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Jamia Millia Islamia',
    shortName: 'JMI',
    domain: 'jmi.ac.in',
    category: 'engineering',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Aligarh Muslim University',
    shortName: 'AMU',
    domain: 'amu.ac.in',
    category: 'engineering',
    state: 'Uttar Pradesh',
    city: 'Aligarh',
    tier: 'tier-1',
  },
  {
    name: 'Manipal Academy of Higher Education',
    shortName: 'MAHE',
    domain: 'manipal.edu',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Manipal',
    tier: 'tier-1',
  },
  {
    name: 'Thapar Institute of Engineering and Technology',
    shortName: 'TIET',
    domain: 'thapar.edu',
    category: 'engineering',
    state: 'Punjab',
    city: 'Patiala',
    tier: 'tier-2',
  },
  {
    name: 'PES University',
    shortName: 'PES',
    domain: 'pes.edu',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-2',
  },
  {
    name: 'R.V. College of Engineering',
    shortName: 'RVCE',
    domain: 'rvce.edu.in',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-2',
  },
  {
    name: 'BMS College of Engineering',
    shortName: 'BMSCE',
    domain: 'bmsce.ac.in',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-2',
  },
  {
    name: 'M.S. Ramaiah Institute of Technology',
    shortName: 'MSRIT',
    domain: 'msrit.edu',
    category: 'engineering',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-2',
  },
  {
    name: 'College of Engineering, Pune',
    shortName: 'COEP',
    domain: 'coep.ac.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Veermata Jijabai Technological Institute',
    shortName: 'VJTI',
    domain: 'vjti.ac.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Sardar Patel Institute of Technology',
    shortName: 'SPIT',
    domain: 'spit.ac.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-2',
  },
  {
    name: 'Birla Institute of Technology Mesra',
    shortName: 'BIT Mesra',
    domain: 'bitmesra.ac.in',
    category: 'engineering',
    state: 'Jharkhand',
    city: 'Ranchi',
    tier: 'tier-1',
  },
  {
    name: 'PSG College of Technology',
    shortName: 'PSG',
    domain: 'psgtech.edu',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    tier: 'tier-2',
  },
  {
    name: 'Coimbatore Institute of Technology',
    shortName: 'CIT',
    domain: 'cit.edu.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    tier: 'tier-2',
  },
  {
    name: 'SSN College of Engineering',
    shortName: 'SSN',
    domain: 'ssn.edu.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-2',
  },
  {
    name: 'SRM Institute of Science and Technology',
    shortName: 'SRM',
    domain: 'srmist.edu.in',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-2',
  },
  {
    name: 'Amrita Vishwa Vidyapeetham',
    shortName: 'Amrita',
    domain: 'amrita.edu',
    category: 'engineering',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    tier: 'tier-1',
  },
  {
    name: 'Shiv Nadar University',
    shortName: 'SNU',
    domain: 'snu.edu.in',
    category: 'engineering',
    state: 'Uttar Pradesh',
    city: 'Greater Noida',
    tier: 'tier-1',
  },
  {
    name: 'Lovely Professional University',
    shortName: 'LPU',
    domain: 'lpu.in',
    category: 'engineering',
    state: 'Punjab',
    city: 'Phagwara',
    tier: 'tier-2',
  },
  {
    name: 'Chandigarh University',
    shortName: 'CU',
    domain: 'cuchd.in',
    category: 'engineering',
    state: 'Punjab',
    city: 'Mohali',
    tier: 'tier-2',
  },
  {
    name: 'Amity University Noida',
    shortName: 'Amity',
    domain: 'amity.edu',
    category: 'engineering',
    state: 'Uttar Pradesh',
    city: 'Noida',
    tier: 'tier-2',
  },
  {
    name: 'KIIT University Bhubaneswar',
    shortName: 'KIIT',
    domain: 'kiit.ac.in',
    category: 'engineering',
    state: 'Odisha',
    city: 'Bhubaneswar',
    tier: 'tier-2',
  },
  {
    name: 'Symbiosis Institute of Technology',
    shortName: 'SIT',
    domain: 'sitpune.edu.in',
    category: 'engineering',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-2',
  },
  {
    name: 'Indian School of Mines (now IIT ISM)',
    shortName: 'ISM',
    domain: 'iitism.ac.in',
    category: 'engineering',
    state: 'Jharkhand',
    city: 'Dhanbad',
    tier: 'tier-1',
  },
];

// ---------- IIMs (all 20) ----------
const IIMS: InstitutionSeed[] = [
  {
    name: 'Indian Institute of Management Ahmedabad',
    shortName: 'IIM-A',
    domain: 'iima.ac.in',
    category: 'management',
    nirfRank: 1,
    state: 'Gujarat',
    city: 'Ahmedabad',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Bangalore',
    shortName: 'IIM-B',
    domain: 'iimb.ac.in',
    category: 'management',
    nirfRank: 2,
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Calcutta',
    shortName: 'IIM-C',
    domain: 'iimcal.ac.in',
    category: 'management',
    nirfRank: 3,
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Lucknow',
    shortName: 'IIM-L',
    domain: 'iiml.ac.in',
    category: 'management',
    nirfRank: 7,
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Kozhikode',
    shortName: 'IIM-K',
    domain: 'iimk.ac.in',
    category: 'management',
    nirfRank: 4,
    state: 'Kerala',
    city: 'Kozhikode',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Indore',
    shortName: 'IIM-I',
    domain: 'iimidr.ac.in',
    category: 'management',
    nirfRank: 8,
    state: 'Madhya Pradesh',
    city: 'Indore',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Shillong',
    shortName: 'IIM-Shg',
    domain: 'iimshillong.ac.in',
    category: 'management',
    nirfRank: 25,
    state: 'Meghalaya',
    city: 'Shillong',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Rohtak',
    shortName: 'IIM-R',
    domain: 'iimrohtak.ac.in',
    category: 'management',
    nirfRank: 19,
    state: 'Haryana',
    city: 'Rohtak',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Ranchi',
    shortName: 'IIM-Ran',
    domain: 'iimranchi.ac.in',
    category: 'management',
    nirfRank: 30,
    state: 'Jharkhand',
    city: 'Ranchi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Raipur',
    shortName: 'IIM-Rai',
    domain: 'iimraipur.ac.in',
    category: 'management',
    state: 'Chhattisgarh',
    city: 'Raipur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Tiruchirappalli',
    shortName: 'IIM-T',
    domain: 'iimtrichy.ac.in',
    category: 'management',
    nirfRank: 18,
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Udaipur',
    shortName: 'IIM-U',
    domain: 'iimu.ac.in',
    category: 'management',
    nirfRank: 22,
    state: 'Rajasthan',
    city: 'Udaipur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Kashipur',
    shortName: 'IIM-Ksh',
    domain: 'iimkashipur.ac.in',
    category: 'management',
    nirfRank: 35,
    state: 'Uttarakhand',
    city: 'Kashipur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Nagpur',
    shortName: 'IIM-Nag',
    domain: 'iimnagpur.ac.in',
    category: 'management',
    state: 'Maharashtra',
    city: 'Nagpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Amritsar',
    shortName: 'IIM-Amr',
    domain: 'iimamritsar.ac.in',
    category: 'management',
    state: 'Punjab',
    city: 'Amritsar',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Bodh Gaya',
    shortName: 'IIM-BG',
    domain: 'iimbg.ac.in',
    category: 'management',
    state: 'Bihar',
    city: 'Bodh Gaya',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Sirmaur',
    shortName: 'IIM-Sir',
    domain: 'iimsirmaur.ac.in',
    category: 'management',
    state: 'Himachal Pradesh',
    city: 'Sirmaur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Sambalpur',
    shortName: 'IIM-Sambalpur',
    domain: 'iimsambalpur.ac.in',
    category: 'management',
    state: 'Odisha',
    city: 'Sambalpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Visakhapatnam',
    shortName: 'IIM-V',
    domain: 'iimv.ac.in',
    category: 'management',
    state: 'Andhra Pradesh',
    city: 'Visakhapatnam',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Jammu',
    shortName: 'IIM-Jmu',
    domain: 'iimj.ac.in',
    category: 'management',
    state: 'Jammu and Kashmir',
    city: 'Jammu',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Management Mumbai',
    shortName: 'IIM-Mum',
    domain: 'iimmumbai.ac.in',
    category: 'management',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
];

// ---------- Other top management ----------
const OTHER_MGMT: InstitutionSeed[] = [
  {
    name: 'XLRI Jamshedpur',
    shortName: 'XLRI',
    domain: 'xlri.ac.in',
    category: 'management',
    nirfRank: 9,
    state: 'Jharkhand',
    city: 'Jamshedpur',
    tier: 'tier-1',
  },
  {
    name: 'Management Development Institute Gurgaon',
    shortName: 'MDI',
    domain: 'mdi.ac.in',
    category: 'management',
    nirfRank: 14,
    state: 'Haryana',
    city: 'Gurgaon',
    tier: 'tier-1',
  },
  {
    name: 'S.P. Jain Institute of Management and Research',
    shortName: 'SPJIMR',
    domain: 'spjimr.org',
    category: 'management',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Indian School of Business',
    shortName: 'ISB',
    domain: 'isb.edu',
    category: 'management',
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'Faculty of Management Studies, Delhi',
    shortName: 'FMS Delhi',
    domain: 'fms.edu',
    category: 'management',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Symbiosis Institute of Business Management Pune',
    shortName: 'SIBM-P',
    domain: 'sibm.edu',
    category: 'management',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Narsee Monjee Institute of Management Studies',
    shortName: 'NMIMS',
    domain: 'nmims.edu',
    category: 'management',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'IMI Delhi',
    shortName: 'IMI',
    domain: 'imi.edu',
    category: 'management',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Goa Institute of Management',
    shortName: 'GIM',
    domain: 'gim.ac.in',
    category: 'management',
    state: 'Goa',
    city: 'Sanquelim',
    tier: 'tier-2',
  },
  {
    name: 'TAPMI Manipal',
    shortName: 'TAPMI',
    domain: 'tapmi.edu.in',
    category: 'management',
    state: 'Karnataka',
    city: 'Manipal',
    tier: 'tier-2',
  },
  {
    name: 'XIM Bhubaneswar',
    shortName: 'XIMB',
    domain: 'xim.edu.in',
    category: 'management',
    state: 'Odisha',
    city: 'Bhubaneswar',
    tier: 'tier-2',
  },
  {
    name: 'Great Lakes Institute of Management',
    shortName: 'GLIM',
    domain: 'greatlakes.edu.in',
    category: 'management',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-2',
  },
  {
    name: 'BIM Trichy',
    shortName: 'BIM',
    domain: 'bim.edu',
    category: 'management',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    tier: 'tier-2',
  },
];

// ---------- NLUs (all 25) ----------
const NLUS: InstitutionSeed[] = [
  {
    name: 'National Law School of India University',
    shortName: 'NLSIU',
    domain: 'nls.ac.in',
    category: 'law',
    nirfRank: 1,
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'National Academy of Legal Studies and Research',
    shortName: 'NALSAR',
    domain: 'nalsar.ac.in',
    category: 'law',
    nirfRank: 3,
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Delhi',
    shortName: 'NLU-D',
    domain: 'nludelhi.ac.in',
    category: 'law',
    nirfRank: 2,
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Jodhpur',
    shortName: 'NLU-J',
    domain: 'nlujodhpur.ac.in',
    category: 'law',
    nirfRank: 8,
    state: 'Rajasthan',
    city: 'Jodhpur',
    tier: 'tier-1',
  },
  {
    name: 'West Bengal National University of Juridical Sciences',
    shortName: 'NUJS',
    domain: 'nujs.edu',
    category: 'law',
    nirfRank: 5,
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: 'Gujarat National Law University',
    shortName: 'GNLU',
    domain: 'gnlu.ac.in',
    category: 'law',
    nirfRank: 12,
    state: 'Gujarat',
    city: 'Gandhinagar',
    tier: 'tier-1',
  },
  {
    name: 'Hidayatullah National Law University',
    shortName: 'HNLU',
    domain: 'hnlu.ac.in',
    category: 'law',
    state: 'Chhattisgarh',
    city: 'Raipur',
    tier: 'tier-1',
  },
  {
    name: 'Rajiv Gandhi National University of Law',
    shortName: 'RGNUL',
    domain: 'rgnul.ac.in',
    category: 'law',
    state: 'Punjab',
    city: 'Patiala',
    tier: 'tier-1',
  },
  {
    name: 'Chanakya National Law University',
    shortName: 'CNLU',
    domain: 'cnlu.ac.in',
    category: 'law',
    state: 'Bihar',
    city: 'Patna',
    tier: 'tier-1',
  },
  {
    name: 'National University of Advanced Legal Studies',
    shortName: 'NUALS',
    domain: 'nuals.ac.in',
    category: 'law',
    state: 'Kerala',
    city: 'Kochi',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Odisha',
    shortName: 'NLUO',
    domain: 'nluo.ac.in',
    category: 'law',
    state: 'Odisha',
    city: 'Cuttack',
    tier: 'tier-1',
  },
  {
    name: 'National University of Study and Research in Law',
    shortName: 'NUSRL',
    domain: 'nusrlranchi.ac.in',
    category: 'law',
    state: 'Jharkhand',
    city: 'Ranchi',
    tier: 'tier-1',
  },
  {
    name: 'National Law University and Judicial Academy Assam',
    shortName: 'NLUJA',
    domain: 'nluassam.ac.in',
    category: 'law',
    state: 'Assam',
    city: 'Guwahati',
    tier: 'tier-1',
  },
  {
    name: 'Damodaram Sanjivayya National Law University',
    shortName: 'DSNLU',
    domain: 'dsnlu.ac.in',
    category: 'law',
    state: 'Andhra Pradesh',
    city: 'Visakhapatnam',
    tier: 'tier-1',
  },
  {
    name: 'The Tamil Nadu National Law University',
    shortName: 'TNNLU',
    domain: 'tnnlu.ac.in',
    category: 'law',
    state: 'Tamil Nadu',
    city: 'Tiruchirappalli',
    tier: 'tier-1',
  },
  {
    name: 'Maharashtra National Law University Mumbai',
    shortName: 'MNLU-M',
    domain: 'mnlumumbai.edu.in',
    category: 'law',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Maharashtra National Law University Nagpur',
    shortName: 'MNLU-N',
    domain: 'mnlunagpur.edu.in',
    category: 'law',
    state: 'Maharashtra',
    city: 'Nagpur',
    tier: 'tier-1',
  },
  {
    name: 'Maharashtra National Law University Aurangabad',
    shortName: 'MNLU-A',
    domain: 'mnlua.ac.in',
    category: 'law',
    state: 'Maharashtra',
    city: 'Aurangabad',
    tier: 'tier-1',
  },
  {
    name: 'Himachal Pradesh National Law University',
    shortName: 'HPNLU',
    domain: 'hpnlu.ac.in',
    category: 'law',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    tier: 'tier-1',
  },
  {
    name: 'Dharmashastra National Law University',
    shortName: 'DNLU',
    domain: 'mpdnlu.ac.in',
    category: 'law',
    state: 'Madhya Pradesh',
    city: 'Jabalpur',
    tier: 'tier-1',
  },
  {
    name: 'Dr. B. R. Ambedkar National Law University Sonipat',
    shortName: 'BRANLU',
    domain: 'dbranlu.ac.in',
    category: 'law',
    state: 'Haryana',
    city: 'Sonipat',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Tripura',
    shortName: 'NLU-Tri',
    domain: 'nlutripura.ac.in',
    category: 'law',
    state: 'Tripura',
    city: 'Agartala',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Meghalaya',
    shortName: 'NLU-Meg',
    domain: 'nlumeghalaya.ac.in',
    category: 'law',
    state: 'Meghalaya',
    city: 'Shillong',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Shimla',
    shortName: 'HPNLU-S',
    domain: 'hpnlu.ac.in',
    category: 'law',
    state: 'Himachal Pradesh',
    city: 'Shimla',
    tier: 'tier-1',
  },
  {
    name: 'National Law University Jharkhand',
    shortName: 'NUSRL-J',
    domain: 'nusrl.ac.in',
    category: 'law',
    state: 'Jharkhand',
    city: 'Ranchi',
    tier: 'tier-1',
  },
];

// ---------- IISERs + IISc ----------
const SCIENCE_RESEARCH: InstitutionSeed[] = [
  {
    name: 'Indian Institute of Science Bangalore',
    shortName: 'IISc',
    domain: 'iisc.ac.in',
    category: 'science',
    nirfRank: 1,
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Pune',
    shortName: 'IISER-P',
    domain: 'iiserpune.ac.in',
    category: 'science',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Kolkata',
    shortName: 'IISER-K',
    domain: 'iiserkol.ac.in',
    category: 'science',
    state: 'West Bengal',
    city: 'Mohanpur',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Mohali',
    shortName: 'IISER-M',
    domain: 'iisermohali.ac.in',
    category: 'science',
    state: 'Punjab',
    city: 'Mohali',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Bhopal',
    shortName: 'IISER-B',
    domain: 'iiserb.ac.in',
    category: 'science',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Thiruvananthapuram',
    shortName: 'IISER-TVM',
    domain: 'iisertvm.ac.in',
    category: 'science',
    state: 'Kerala',
    city: 'Thiruvananthapuram',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Tirupati',
    shortName: 'IISER-Tirupati',
    domain: 'iisertirupati.ac.in',
    category: 'science',
    state: 'Andhra Pradesh',
    city: 'Tirupati',
    tier: 'tier-1',
  },
  {
    name: 'Indian Institute of Science Education and Research Berhampur',
    shortName: 'IISER-Berhampur',
    domain: 'iiserbpr.ac.in',
    category: 'science',
    state: 'Odisha',
    city: 'Berhampur',
    tier: 'tier-1',
  },
  {
    name: 'Tata Institute of Fundamental Research',
    shortName: 'TIFR',
    domain: 'tifr.res.in',
    category: 'science',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Science Education and Research',
    shortName: 'NISER',
    domain: 'niser.ac.in',
    category: 'science',
    state: 'Odisha',
    city: 'Bhubaneswar',
    tier: 'tier-1',
  },
];

// ---------- Delhi University & SRCC + other top commerce ----------
const DU_COMMERCE: InstitutionSeed[] = [
  {
    name: 'University of Delhi',
    shortName: 'DU',
    domain: 'du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Shri Ram College of Commerce',
    shortName: 'SRCC',
    domain: 'srcc.edu',
    category: 'commerce',
    nirfRank: 1,
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Lady Shri Ram College for Women',
    shortName: 'LSR',
    domain: 'lsr.edu.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Hindu College',
    shortName: 'Hindu',
    domain: 'hinducollege.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: "St. Stephen's College",
    shortName: 'Stephens',
    domain: 'ststephens.edu',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Miranda House',
    shortName: 'MH',
    domain: 'mirandahouse.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Hansraj College',
    shortName: 'HRC',
    domain: 'hansrajcollege.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Kirori Mal College',
    shortName: 'KMC',
    domain: 'kmc.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Ramjas College',
    shortName: 'Ramjas',
    domain: 'ramjas.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Sri Venkateswara College',
    shortName: 'SVC',
    domain: 'svc.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Gargi College',
    shortName: 'Gargi',
    domain: 'gargi.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Jesus and Mary College',
    shortName: 'JMC',
    domain: 'jmc.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Indraprastha College for Women',
    shortName: 'IPCW',
    domain: 'ipcollege.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Sri Aurobindo College',
    shortName: 'SAC',
    domain: 'aurobindo.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Daulat Ram College',
    shortName: 'DRC',
    domain: 'dr.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Deshbandhu College',
    shortName: 'DBC',
    domain: 'deshbandhucollege.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Kamala Nehru College',
    shortName: 'KNC',
    domain: 'knc.edu.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Maitreyi College',
    shortName: 'Maitreyi',
    domain: 'maitreyi.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Atma Ram Sanatan Dharma College',
    shortName: 'ARSD',
    domain: 'arsd.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Dyal Singh College',
    shortName: 'DSC',
    domain: 'dsc.du.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'PGDAV College',
    shortName: 'PGDAV',
    domain: 'pgdavcollege.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Shaheed Bhagat Singh College',
    shortName: 'SBSC',
    domain: 'sbsc.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  // Top non-DU commerce
  {
    name: 'Loyola College Chennai',
    shortName: 'Loyola',
    domain: 'loyolacollege.edu',
    category: 'commerce',
    nirfRank: 7,
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: "St. Xavier's College Kolkata",
    shortName: 'SXC',
    domain: 'sxccal.edu',
    category: 'commerce',
    nirfRank: 10,
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: "St. Xavier's College Mumbai",
    shortName: 'SXC-M',
    domain: 'xaviers.edu',
    category: 'commerce',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Christ University Bangalore',
    shortName: 'Christ',
    domain: 'christuniversity.in',
    category: 'commerce',
    nirfRank: 13,
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'Madras Christian College',
    shortName: 'MCC',
    domain: 'mcc.edu.in',
    category: 'commerce',
    nirfRank: 22,
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'PSGR Krishnammal College for Women',
    shortName: 'PSGR',
    domain: 'psgrkcw.ac.in',
    category: 'commerce',
    state: 'Tamil Nadu',
    city: 'Coimbatore',
    tier: 'tier-1',
  },
  {
    name: 'Symbiosis College of Arts and Commerce',
    shortName: 'SCAC',
    domain: 'symbiosiscollege.edu.in',
    category: 'commerce',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Narsee Monjee College of Commerce and Economics',
    shortName: 'NM',
    domain: 'nmcce.org',
    category: 'commerce',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'H.R. College of Commerce and Economics',
    shortName: 'HR',
    domain: 'hrcollege.edu',
    category: 'commerce',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'Stella Maris College Chennai',
    shortName: 'Stella',
    domain: 'stellamariscollege.edu.in',
    category: 'commerce',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Ethiraj College for Women',
    shortName: 'Ethiraj',
    domain: 'ethirajcollege.in',
    category: 'commerce',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Mount Carmel College Bangalore',
    shortName: 'MCC-B',
    domain: 'mccblr.edu.in',
    category: 'commerce',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: "St. Joseph's College of Commerce",
    shortName: 'SJCC',
    domain: 'sjcc.edu.in',
    category: 'commerce',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
];

// ---------- Major state universities & general ----------
const STATE_GENERAL: InstitutionSeed[] = [
  {
    name: 'Jawaharlal Nehru University',
    shortName: 'JNU',
    domain: 'jnu.ac.in',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'University of Hyderabad',
    shortName: 'UoH',
    domain: 'uohyd.ac.in',
    category: 'arts',
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'University of Calcutta',
    shortName: 'CU',
    domain: 'caluniv.ac.in',
    category: 'arts',
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: 'University of Mumbai',
    shortName: 'MU',
    domain: 'mu.ac.in',
    category: 'arts',
    state: 'Maharashtra',
    city: 'Mumbai',
    tier: 'tier-1',
  },
  {
    name: 'University of Madras',
    shortName: 'UnoM',
    domain: 'unom.ac.in',
    category: 'arts',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
  {
    name: 'Banaras Hindu University',
    shortName: 'BHU',
    domain: 'bhu.ac.in',
    category: 'arts',
    state: 'Uttar Pradesh',
    city: 'Varanasi',
    tier: 'tier-1',
  },
  {
    name: 'Savitribai Phule Pune University',
    shortName: 'SPPU',
    domain: 'unipune.ac.in',
    category: 'arts',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'Osmania University',
    shortName: 'OU',
    domain: 'osmania.ac.in',
    category: 'arts',
    state: 'Telangana',
    city: 'Hyderabad',
    tier: 'tier-1',
  },
  {
    name: 'Cochin University of Science and Technology',
    shortName: 'CUSAT',
    domain: 'cusat.ac.in',
    category: 'engineering',
    state: 'Kerala',
    city: 'Kochi',
    tier: 'tier-1',
  },
  {
    name: 'Pondicherry University',
    shortName: 'PU',
    domain: 'pondiuni.edu.in',
    category: 'arts',
    state: 'Puducherry',
    city: 'Puducherry',
    tier: 'tier-1',
  },
  {
    name: 'Tezpur University',
    shortName: 'TU',
    domain: 'tezu.ernet.in',
    category: 'arts',
    state: 'Assam',
    city: 'Tezpur',
    tier: 'tier-1',
  },
  {
    name: 'University of Allahabad',
    shortName: 'UoA',
    domain: 'allduniv.ac.in',
    category: 'arts',
    state: 'Uttar Pradesh',
    city: 'Prayagraj',
    tier: 'tier-1',
  },
  {
    name: 'Punjab University Chandigarh',
    shortName: 'PU-Ch',
    domain: 'puchd.ac.in',
    category: 'arts',
    state: 'Chandigarh',
    city: 'Chandigarh',
    tier: 'tier-1',
  },
  {
    name: 'Jamia Hamdard',
    shortName: 'JH',
    domain: 'jamiahamdard.edu',
    category: 'arts',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'O.P. Jindal Global University',
    shortName: 'JGU',
    domain: 'jgu.edu.in',
    category: 'law',
    state: 'Haryana',
    city: 'Sonipat',
    tier: 'tier-1',
  },
  {
    name: 'Ashoka University',
    shortName: 'Ashoka',
    domain: 'ashoka.edu.in',
    category: 'arts',
    state: 'Haryana',
    city: 'Sonipat',
    tier: 'tier-1',
  },
  {
    name: 'Krea University',
    shortName: 'Krea',
    domain: 'krea.edu.in',
    category: 'arts',
    state: 'Andhra Pradesh',
    city: 'Sri City',
    tier: 'tier-2',
  },
  {
    name: 'Symbiosis International University',
    shortName: 'SIU',
    domain: 'siu.edu.in',
    category: 'arts',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'TERI School of Advanced Studies',
    shortName: 'TERI',
    domain: 'terisas.ac.in',
    category: 'science',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Indian Statistical Institute',
    shortName: 'ISI',
    domain: 'isical.ac.in',
    category: 'science',
    state: 'West Bengal',
    city: 'Kolkata',
    tier: 'tier-1',
  },
  {
    name: 'Chennai Mathematical Institute',
    shortName: 'CMI',
    domain: 'cmi.ac.in',
    category: 'science',
    state: 'Tamil Nadu',
    city: 'Chennai',
    tier: 'tier-1',
  },
];

// ---------- Top medical ----------
const MEDICAL: InstitutionSeed[] = [
  {
    name: 'All India Institute of Medical Sciences Delhi',
    shortName: 'AIIMS Delhi',
    domain: 'aiims.edu',
    category: 'medical',
    nirfRank: 1,
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Post Graduate Institute of Medical Education and Research',
    shortName: 'PGIMER',
    domain: 'pgimer.edu.in',
    category: 'medical',
    nirfRank: 2,
    state: 'Chandigarh',
    city: 'Chandigarh',
    tier: 'tier-1',
  },
  {
    name: 'Christian Medical College Vellore',
    shortName: 'CMC',
    domain: 'cmcvellore.ac.in',
    category: 'medical',
    nirfRank: 3,
    state: 'Tamil Nadu',
    city: 'Vellore',
    tier: 'tier-1',
  },
  {
    name: 'National Institute of Mental Health and Neurosciences',
    shortName: 'NIMHANS',
    domain: 'nimhans.ac.in',
    category: 'medical',
    state: 'Karnataka',
    city: 'Bangalore',
    tier: 'tier-1',
  },
  {
    name: 'Jawaharlal Institute of Postgraduate Medical Education and Research',
    shortName: 'JIPMER',
    domain: 'jipmer.edu.in',
    category: 'medical',
    state: 'Puducherry',
    city: 'Puducherry',
    tier: 'tier-1',
  },
  {
    name: 'Kasturba Medical College Manipal',
    shortName: 'KMC-M',
    domain: 'manipal.edu',
    category: 'medical',
    state: 'Karnataka',
    city: 'Manipal',
    tier: 'tier-1',
  },
  {
    name: "King George's Medical University",
    shortName: 'KGMU',
    domain: 'kgmu.org',
    category: 'medical',
    state: 'Uttar Pradesh',
    city: 'Lucknow',
    tier: 'tier-1',
  },
  {
    name: 'Maulana Azad Medical College',
    shortName: 'MAMC',
    domain: 'mamc.delhi.gov.in',
    category: 'medical',
    state: 'Delhi',
    city: 'New Delhi',
    tier: 'tier-1',
  },
  {
    name: 'Armed Forces Medical College',
    shortName: 'AFMC',
    domain: 'afmc.nic.in',
    category: 'medical',
    state: 'Maharashtra',
    city: 'Pune',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Bhubaneswar',
    shortName: 'AIIMS BBSR',
    domain: 'aiimsbhubaneswar.nic.in',
    category: 'medical',
    state: 'Odisha',
    city: 'Bhubaneswar',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Jodhpur',
    shortName: 'AIIMS J',
    domain: 'aiimsjodhpur.edu.in',
    category: 'medical',
    state: 'Rajasthan',
    city: 'Jodhpur',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Patna',
    shortName: 'AIIMS P',
    domain: 'aiimspatna.org',
    category: 'medical',
    state: 'Bihar',
    city: 'Patna',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Raipur',
    shortName: 'AIIMS R',
    domain: 'aiimsraipur.edu.in',
    category: 'medical',
    state: 'Chhattisgarh',
    city: 'Raipur',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Rishikesh',
    shortName: 'AIIMS Rsh',
    domain: 'aiimsrishikesh.edu.in',
    category: 'medical',
    state: 'Uttarakhand',
    city: 'Rishikesh',
    tier: 'tier-1',
  },
  {
    name: 'AIIMS Bhopal',
    shortName: 'AIIMS Bh',
    domain: 'aiimsbhopal.edu.in',
    category: 'medical',
    state: 'Madhya Pradesh',
    city: 'Bhopal',
    tier: 'tier-1',
  },
];

// De-dupe by name (some legitimate collisions e.g. IIIT-D appears twice).
const ALL_RAW: InstitutionSeed[] = [
  ...IITS,
  ...NITS,
  ...IIITS,
  ...OTHER_ENG,
  ...IIMS,
  ...OTHER_MGMT,
  ...NLUS,
  ...SCIENCE_RESEARCH,
  ...DU_COMMERCE,
  ...STATE_GENERAL,
  ...MEDICAL,
];

const seen = new Set<string>();
export const INSTITUTION_SEEDS: InstitutionSeed[] = ALL_RAW.filter((i) => {
  const key = i.name.toLowerCase();
  if (seen.has(key)) return false;
  seen.add(key);
  return true;
});
