// Curated catalog of ~200 skills across categories.
// Used by seed.ts.

type SkillSeed = { name: string; category: string; parent?: string };

const lang = (n: string) => ({ name: n, category: 'Programming Languages' });
const fw = (n: string) => ({ name: n, category: 'Frameworks & Libraries' });
const db = (n: string) => ({ name: n, category: 'Databases' });
const cloud = (n: string) => ({ name: n, category: 'Cloud & DevOps' });
const data = (n: string) => ({ name: n, category: 'Data & ML' });
const sec = (n: string) => ({ name: n, category: 'Security' });
const mobile = (n: string) => ({ name: n, category: 'Mobile' });
const tooling = (n: string) => ({ name: n, category: 'Tools & Methodologies' });
const design = (n: string) => ({ name: n, category: 'Design' });
const soft = (n: string) => ({ name: n, category: 'Soft Skills' });
const business = (n: string) => ({ name: n, category: 'Business & Product' });
const law = (n: string) => ({ name: n, category: 'Law' });
const commerce = (n: string) => ({ name: n, category: 'Commerce & Finance' });
const mgmt = (n: string) => ({ name: n, category: 'Management' });
const cocur = (n: string) => ({ name: n, category: 'Co-curricular' });

export const SKILL_SEEDS: SkillSeed[] = [
  // Languages
  lang('JavaScript'),
  lang('TypeScript'),
  lang('Python'),
  lang('Java'),
  lang('C'),
  lang('C++'),
  lang('C#'),
  lang('Go'),
  lang('Rust'),
  lang('Kotlin'),
  lang('Swift'),
  lang('Ruby'),
  lang('PHP'),
  lang('Scala'),
  lang('R'),
  lang('Dart'),
  lang('Elixir'),
  lang('Haskell'),
  lang('Lua'),
  lang('Bash'),
  lang('SQL'),
  lang('Solidity'),
  lang('Perl'),
  lang('MATLAB'),
  lang('Julia'),

  // Frontend frameworks
  fw('React'),
  fw('Next.js'),
  fw('Vue.js'),
  fw('Nuxt.js'),
  fw('Svelte'),
  fw('SvelteKit'),
  fw('Angular'),
  fw('Remix'),
  fw('Astro'),
  fw('Solid.js'),
  fw('Redux'),
  fw('Zustand'),
  fw('TanStack Query'),
  fw('Tailwind CSS'),
  fw('Sass'),
  fw('Material UI'),
  fw('shadcn/ui'),
  fw('Chakra UI'),
  fw('Framer Motion'),
  fw('Three.js'),
  fw('D3.js'),

  // Backend frameworks
  fw('Node.js'),
  fw('Express'),
  fw('NestJS'),
  fw('Fastify'),
  fw('Koa'),
  fw('Django'),
  fw('Flask'),
  fw('FastAPI'),
  fw('Spring Boot'),
  fw('Ruby on Rails'),
  fw('Laravel'),
  fw('ASP.NET Core'),
  fw('Gin'),
  fw('Echo'),
  fw('Actix'),
  fw('GraphQL'),
  fw('tRPC'),
  fw('Prisma'),
  fw('SQLAlchemy'),
  fw('Hibernate'),
  fw('Sequelize'),
  fw('Drizzle'),

  // Mobile
  mobile('React Native'),
  mobile('Flutter'),
  mobile('SwiftUI'),
  mobile('UIKit'),
  mobile('Jetpack Compose'),
  mobile('Android SDK'),
  mobile('Ionic'),
  mobile('Expo'),

  // Databases
  db('PostgreSQL'),
  db('MySQL'),
  db('MongoDB'),
  db('SQLite'),
  db('Redis'),
  db('Cassandra'),
  db('DynamoDB'),
  db('Elasticsearch'),
  db('Neo4j'),
  db('ClickHouse'),
  db('Snowflake'),
  db('BigQuery'),
  db('Firebase'),
  db('Supabase'),
  db('Meilisearch'),
  db('pgvector'),
  db('Pinecone'),

  // Cloud / DevOps
  cloud('AWS'),
  cloud('Google Cloud Platform'),
  cloud('Microsoft Azure'),
  cloud('Cloudflare'),
  cloud('Vercel'),
  cloud('Netlify'),
  cloud('Heroku'),
  cloud('Railway'),
  cloud('Docker'),
  cloud('Kubernetes'),
  cloud('Helm'),
  cloud('Terraform'),
  cloud('Pulumi'),
  cloud('Ansible'),
  cloud('GitHub Actions'),
  cloud('GitLab CI'),
  cloud('Jenkins'),
  cloud('CircleCI'),
  cloud('Nginx'),
  cloud('Linux'),
  cloud('Bash Scripting'),
  cloud('Prometheus'),
  cloud('Grafana'),
  cloud('Datadog'),
  cloud('Sentry'),

  // Data / ML
  data('NumPy'),
  data('Pandas'),
  data('Scikit-learn'),
  data('TensorFlow'),
  data('PyTorch'),
  data('Keras'),
  data('Hugging Face Transformers'),
  data('LangChain'),
  data('LlamaIndex'),
  data('OpenAI API'),
  data('Anthropic API'),
  data('Apache Spark'),
  data('Apache Kafka'),
  data('Apache Airflow'),
  data('dbt'),
  data('Tableau'),
  data('Power BI'),
  data('Jupyter'),
  data('Computer Vision'),
  data('NLP'),
  data('Reinforcement Learning'),
  data('MLOps'),
  data('Feature Engineering'),

  // Security
  sec('OWASP Top 10'),
  sec('Penetration Testing'),
  sec('Cryptography'),
  sec('Authentication & OAuth'),
  sec('Burp Suite'),
  sec('Nmap'),
  sec('Metasploit'),
  sec('Wireshark'),
  sec('SIEM'),
  sec('Zero Trust Architecture'),

  // Tools
  tooling('Git'),
  tooling('GitHub'),
  tooling('Jira'),
  tooling('Linear'),
  tooling('Notion'),
  tooling('Figma'),
  tooling('Postman'),
  tooling('Vite'),
  tooling('Webpack'),
  tooling('ESLint'),
  tooling('Prettier'),
  tooling('Jest'),
  tooling('Vitest'),
  tooling('Playwright'),
  tooling('Cypress'),
  tooling('Storybook'),
  tooling('Agile'),
  tooling('Scrum'),
  tooling('Kanban'),
  tooling('TDD'),

  // Design
  design('UI Design'),
  design('UX Research'),
  design('Figma Design'),
  design('Wireframing'),
  design('Prototyping'),
  design('Design Systems'),
  design('Accessibility (a11y)'),

  // Business / Product
  business('Product Management'),
  business('Technical Writing'),
  business('A/B Testing'),
  business('Analytics'),
  business('Growth'),
  business('SEO'),

  // Soft
  soft('Communication'),
  soft('Team Collaboration'),
  soft('Problem Solving'),
  soft('Time Management'),
  soft('Leadership'),
  soft('Mentoring'),
  soft('Public Speaking'),

  // Law
  law('Legal Research'),
  law('Legal Writing & Drafting'),
  law('Contract Drafting'),
  law('Constitutional Law'),
  law('Criminal Law'),
  law('Corporate & Company Law'),
  law('Civil Litigation'),
  law('Intellectual Property Law'),
  law('Taxation Law'),
  law('Mergers & Acquisitions'),
  law('Compliance & Regulatory'),
  law('Arbitration & Mediation'),
  law('Moot Court'),
  law('Cyber Law'),
  law('International Law'),
  law('Due Diligence'),
  law('Labour & Employment Law'),

  // Commerce & Finance
  commerce('Financial Accounting'),
  commerce('Cost & Management Accounting'),
  commerce('Auditing'),
  commerce('Direct Taxation'),
  commerce('GST & Indirect Taxation'),
  commerce('Financial Modeling'),
  commerce('Equity Research'),
  commerce('Investment Banking'),
  commerce('Corporate Finance'),
  commerce('Financial Analysis'),
  commerce('Tally ERP'),
  commerce('SAP FICO'),
  commerce('Bookkeeping'),
  commerce('Budgeting & Forecasting'),
  commerce('Risk Management'),
  commerce('Portfolio Management'),
  commerce('Banking & Insurance'),
  commerce('Business Economics'),
  commerce('Business Statistics'),

  // Management
  mgmt('Marketing Strategy'),
  mgmt('Digital Marketing'),
  mgmt('Brand Management'),
  mgmt('Sales & Business Development'),
  mgmt('Market Research'),
  mgmt('Operations Management'),
  mgmt('Supply Chain Management'),
  mgmt('Human Resource Management'),
  mgmt('Business Analytics'),
  mgmt('Strategic Management'),
  mgmt('Management Consulting'),
  mgmt('Organizational Behavior'),
  mgmt('Negotiation'),
  mgmt('Content Marketing'),
  mgmt('Social Media Marketing'),
  mgmt('Performance Marketing'),
  mgmt('Customer Relationship Management (CRM)'),
  mgmt('Entrepreneurship'),

  // Co-curricular
  cocur('Debate'),
  cocur('Model United Nations (MUN)'),
  cocur('Quizzing'),
  cocur('Creative Writing'),
  cocur('Content Creation'),
  cocur('Photography'),
  cocur('Videography'),
  cocur('Event Management'),
  cocur('Anchoring & Hosting'),
  cocur('Theatre & Drama'),
  cocur('Journalism'),
  cocur('Blogging'),
  cocur('NSS / NCC'),
  cocur('Volunteering & Social Work'),
  cocur('Sports & Athletics'),
  cocur('Music'),
  cocur('Fine Arts'),
  cocur('Club Leadership'),
];
